syntax = "proto3";
package pb;
option go_package = "github.com/airlangga-hub/microservices/services/account/pb";

message Token {
    string jwt = 1;
}

message SignUpRequest {
    string email = 1;
    string password = 2;
}

message LoginRequest {
    string email = 1;
    string password = 2;
}

message GetAccountRequest {
    int32 account_id = 1;
}

message GetAccountResponse {
    int32 account_id = 1;
    string email = 2;
}

service AccountService {
    rpc SignUp(SignUpRequest) returns (Token);
    rpc Login(LoginRequest) returns (Token);
    rpc GetAccount(GetAccountRequest) returns (GetAccountResponse);
}